clear() --clear the console from last run.

--You need to get the identifier code for the keyboard with name "MACROS"
--This appears about halfway through the SystemID (between two &) and looks like 1BB382AF or some other alphanumeric combo.
--It's usually 7 or 8 characters long.
--Once you have this identifier, replace and uncomment here:
--lmc_device_set_name('MACROS', keyboardIdentifier);
--and delete or comment the next 5 lines

local keyboardIdentifier = '0000AAA'
if keyboardIdentifier == '0000AAA' then
	lmc_assign_keyboard('MACROS');
else lmc_device_set_name('MACROS', keyboardIdentifier);
end

lmc_set_handler('MACROS',function(button, direction)
if (direction == 0) then return end --Activates the press only on the downstroke

lmc.minimizeToTray = true -- Sends LuaMacros to the system tray when you minimize it
--lmc_minimize()  -- starts lua already minimized you shoud activate this (by removing the -- behind it) after everything is set and working

--This lists each key and transforms it into the key+F13
--The lists starts with key number 1 (which doesnt even has an assigned button) it still there just to be sure. 
--The first useful is key 8 which is backspace, and the last is 222 the Single Quote
--the () between the snippets has no real use, it just separates the parts
if (button ==1) then lmc_send_input(124, 0, 0)     --presses F13
                         lmc_send_input(1, 0, 0)   --presses key 1 
                         lmc_send_input(124, 0, 2) --releases F13
                         lmc_send_input(1, 0, 2)   --releases key 1
()
 elseif (button ==2) then lmc_send_input(124, 0, 0)
                         lmc_send_input(2, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(2, 0, 2)
()
 elseif (button ==3) then lmc_send_input(124, 0, 0)
                         lmc_send_input(3, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(3, 0, 2)
()
 elseif (button ==4) then lmc_send_input(124, 0, 0)
                         lmc_send_input(4, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(4, 0, 2)
()
 elseif (button ==5) then lmc_send_input(124, 0, 0)
                         lmc_send_input(5, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(5, 0, 2)
()
 elseif (button ==6) then lmc_send_input(124, 0, 0)
                         lmc_send_input(6, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(6, 0, 2)
()
 elseif (button ==7) then lmc_send_input(124, 0, 0)
                         lmc_send_input(7, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(7, 0, 2)
()
 elseif (button ==8) then lmc_send_input(124, 0, 0)
                         lmc_send_input(8, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(8, 0, 2)
()
 elseif (button ==9) then lmc_send_input(124, 0, 0)
                         lmc_send_input(9, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(9, 0, 2)
()
 elseif (button ==10) then lmc_send_input(124, 0, 0)
                         lmc_send_input(10, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(10, 0, 2)
()
 elseif (button ==11) then lmc_send_input(124, 0, 0)
                         lmc_send_input(11, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(11, 0, 2)
()
 elseif (button ==12) then lmc_send_input(124, 0, 0)
                         lmc_send_input(12, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(12, 0, 2)
()
 elseif (button ==13) then lmc_send_input(124, 0, 0)
                         lmc_send_input(13, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(13, 0, 2)
()
 elseif (button ==14) then lmc_send_input(124, 0, 0)
                         lmc_send_input(14, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(14, 0, 2)
()
 elseif (button ==15) then lmc_send_input(124, 0, 0)
                         lmc_send_input(15, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(15, 0, 2)
()
 elseif (button ==16) then lmc_send_input(124, 0, 0)
                         lmc_send_input(16, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(16, 0, 2)
()
 elseif (button ==17) then lmc_send_input(124, 0, 0)
                         lmc_send_input(17, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(17, 0, 2)
()
 elseif (button ==18) then lmc_send_input(124, 0, 0)
                         lmc_send_input(18, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(18, 0, 2)
()
 elseif (button ==19) then lmc_send_input(124, 0, 0)
                         lmc_send_input(19, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(19, 0, 2)
()
 elseif (button ==20) then lmc_send_input(124, 0, 0)
                         lmc_send_input(20, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(20, 0, 2)
()
 elseif (button ==21) then lmc_send_input(124, 0, 0)
                         lmc_send_input(21, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(21, 0, 2)
()
 elseif (button ==22) then lmc_send_input(124, 0, 0)
                         lmc_send_input(22, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(22, 0, 2)
()
 elseif (button ==23) then lmc_send_input(124, 0, 0)
                         lmc_send_input(23, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(23, 0, 2)
()
 elseif (button ==24) then lmc_send_input(124, 0, 0)
                         lmc_send_input(24, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(24, 0, 2)
()
 elseif (button ==25) then lmc_send_input(124, 0, 0)
                         lmc_send_input(25, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(25, 0, 2)
()
 elseif (button ==26) then lmc_send_input(124, 0, 0)
                         lmc_send_input(26, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(26, 0, 2)
()
 elseif (button ==27) then lmc_send_input(124, 0, 0)
                         lmc_send_input(27, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(27, 0, 2)
()
 elseif (button ==28) then lmc_send_input(124, 0, 0)
                         lmc_send_input(28, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(28, 0, 2)
()
 elseif (button ==29) then lmc_send_input(124, 0, 0)
                         lmc_send_input(29, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(29, 0, 2)
()
 elseif (button ==30) then lmc_send_input(124, 0, 0)
                         lmc_send_input(30, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(30, 0, 2)
()
 elseif (button ==31) then lmc_send_input(124, 0, 0)
                         lmc_send_input(31, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(31, 0, 2)
()
 elseif (button ==32) then lmc_send_input(124, 0, 0)
                         lmc_send_input(32, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(32, 0, 2)
()
 elseif (button ==33) then lmc_send_input(124, 0, 0)
                         lmc_send_input(33, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(33, 0, 2)
()
 elseif (button ==34) then lmc_send_input(124, 0, 0)
                         lmc_send_input(34, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(34, 0, 2)
()
 elseif (button ==35) then lmc_send_input(124, 0, 0)
                         lmc_send_input(35, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(35, 0, 2)
()
 elseif (button ==36) then lmc_send_input(124, 0, 0)
                         lmc_send_input(36, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(36, 0, 2)
()
 elseif (button ==37) then lmc_send_input(124, 0, 0)
                         lmc_send_input(37, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(37, 0, 2)
()
 elseif (button ==38) then lmc_send_input(124, 0, 0)
                         lmc_send_input(38, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(38, 0, 2)
()
 elseif (button ==39) then lmc_send_input(124, 0, 0)
                         lmc_send_input(39, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(39, 0, 2)
()
 elseif (button ==40) then lmc_send_input(124, 0, 0)
                         lmc_send_input(40, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(40, 0, 2)
()
 elseif (button ==41) then lmc_send_input(124, 0, 0)
                         lmc_send_input(41, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(41, 0, 2)
()
 elseif (button ==42) then lmc_send_input(124, 0, 0)
                         lmc_send_input(42, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(42, 0, 2)
()
 elseif (button ==43) then lmc_send_input(124, 0, 0)
                         lmc_send_input(43, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(43, 0, 2)
()
 elseif (button ==44) then lmc_send_input(124, 0, 0)
                         lmc_send_input(44, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(44, 0, 2)
()
 elseif (button ==45) then lmc_send_input(124, 0, 0)
                         lmc_send_input(45, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(45, 0, 2)
()
 elseif (button ==46) then lmc_send_input(124, 0, 0)
                         lmc_send_input(46, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(46, 0, 2)
()
 elseif (button ==47) then lmc_send_input(124, 0, 0)
                         lmc_send_input(47, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(47, 0, 2)
()
 elseif (button ==48) then lmc_send_input(124, 0, 0)
                         lmc_send_input(48, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(48, 0, 2)
()
 elseif (button ==49) then lmc_send_input(124, 0, 0)
                         lmc_send_input(49, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(49, 0, 2)
()
 elseif (button ==50) then lmc_send_input(124, 0, 0)
                         lmc_send_input(50, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(50, 0, 2)
()
 elseif (button ==51) then lmc_send_input(124, 0, 0)
                         lmc_send_input(51, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(51, 0, 2)
()
 elseif (button ==52) then lmc_send_input(124, 0, 0)
                         lmc_send_input(52, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(52, 0, 2)
()
 elseif (button ==53) then lmc_send_input(124, 0, 0)
                         lmc_send_input(53, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(53, 0, 2)
()
 elseif (button ==54) then lmc_send_input(124, 0, 0)
                         lmc_send_input(54, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(54, 0, 2)
()
 elseif (button ==55) then lmc_send_input(124, 0, 0)
                         lmc_send_input(55, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(55, 0, 2)
()
 elseif (button ==56) then lmc_send_input(124, 0, 0)
                         lmc_send_input(56, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(56, 0, 2)
()
 elseif (button ==57) then lmc_send_input(124, 0, 0)
                         lmc_send_input(57, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(57, 0, 2)
()
 elseif (button ==58) then lmc_send_input(124, 0, 0)
                         lmc_send_input(58, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(58, 0, 2)
()
 elseif (button ==59) then lmc_send_input(124, 0, 0)
                         lmc_send_input(59, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(59, 0, 2)
()
 elseif (button ==60) then lmc_send_input(124, 0, 0)
                         lmc_send_input(60, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(60, 0, 2)
()
 elseif (button ==61) then lmc_send_input(124, 0, 0)
                         lmc_send_input(61, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(61, 0, 2)
()
 elseif (button ==62) then lmc_send_input(124, 0, 0)
                         lmc_send_input(62, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(62, 0, 2)
()
 elseif (button ==63) then lmc_send_input(124, 0, 0)
                         lmc_send_input(63, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(63, 0, 2)
()
 elseif (button ==64) then lmc_send_input(124, 0, 0)
                         lmc_send_input(64, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(64, 0, 2)
()
 elseif (button ==65) then lmc_send_input(124, 0, 0)
                         lmc_send_input(65, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(65, 0, 2)
()
 elseif (button ==66) then lmc_send_input(124, 0, 0)
                         lmc_send_input(66, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(66, 0, 2)
()
 elseif (button ==67) then lmc_send_input(124, 0, 0)
                         lmc_send_input(67, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(67, 0, 2)
()
 elseif (button ==68) then lmc_send_input(124, 0, 0)
                         lmc_send_input(68, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(68, 0, 2)
()
 elseif (button ==69) then lmc_send_input(124, 0, 0)
                         lmc_send_input(69, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(69, 0, 2)
()
 elseif (button ==70) then lmc_send_input(124, 0, 0)
                         lmc_send_input(70, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(70, 0, 2)
()
 elseif (button ==71) then lmc_send_input(124, 0, 0)
                         lmc_send_input(71, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(71, 0, 2)
()
 elseif (button ==72) then lmc_send_input(124, 0, 0)
                         lmc_send_input(72, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(72, 0, 2)
()
 elseif (button ==73) then lmc_send_input(124, 0, 0)
                         lmc_send_input(73, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(73, 0, 2)
()
 elseif (button ==74) then lmc_send_input(124, 0, 0)
                         lmc_send_input(74, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(74, 0, 2)
()
 elseif (button ==75) then lmc_send_input(124, 0, 0)
                         lmc_send_input(75, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(75, 0, 2)
()
 elseif (button ==76) then lmc_send_input(124, 0, 0)
                         lmc_send_input(76, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(76, 0, 2)
()
 elseif (button ==77) then lmc_send_input(124, 0, 0)
                         lmc_send_input(77, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(77, 0, 2)
()
 elseif (button ==78) then lmc_send_input(124, 0, 0)
                         lmc_send_input(78, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(78, 0, 2)
()
 elseif (button ==79) then lmc_send_input(124, 0, 0)
                         lmc_send_input(79, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(79, 0, 2)
()
 elseif (button ==80) then lmc_send_input(124, 0, 0)
                         lmc_send_input(80, 0, 0)
                         lmc_send_input(80, 0, 2)
                         lmc_send_input(124, 0, 2)
()
 elseif (button ==81) then lmc_send_input(124, 0, 0)
                         lmc_send_input(81, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(81, 0, 2)
()
 elseif (button ==82) then lmc_send_input(124, 0, 0)
                         lmc_send_input(82, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(82, 0, 2)
()
 elseif (button ==83) then lmc_send_input(124, 0, 0)
                         lmc_send_input(83, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(83, 0, 2)
()
 elseif (button ==84) then lmc_send_input(124, 0, 0)
                         lmc_send_input(84, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(84, 0, 2)
()
 elseif (button ==85) then lmc_send_input(124, 0, 0)
                         lmc_send_input(85, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(85, 0, 2)
()
 elseif (button ==86) then lmc_send_input(124, 0, 0)
                         lmc_send_input(86, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(86, 0, 2)
()
 elseif (button ==87) then lmc_send_input(124, 0, 0)
                         lmc_send_input(87, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(87, 0, 2)
()
 elseif (button ==88) then lmc_send_input(124, 0, 0)
                         lmc_send_input(88, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(88, 0, 2)
()
 elseif (button ==89) then lmc_send_input(124, 0, 0)
                         lmc_send_input(89, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(89, 0, 2)
()
 elseif (button ==90) then lmc_send_input(124, 0, 0)
                         lmc_send_input(90, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(90, 0, 2)
()
 elseif (button ==91) then lmc_send_input(124, 0, 0)
                         lmc_send_input(91, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(91, 0, 2)
()
 elseif (button ==92) then lmc_send_input(124, 0, 0)
                         lmc_send_input(92, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(92, 0, 2)
()
 elseif (button ==93) then lmc_send_input(124, 0, 0)
                         lmc_send_input(93, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(93, 0, 2)
()
 elseif (button ==94) then lmc_send_input(124, 0, 0)
                         lmc_send_input(94, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(94, 0, 2)
()
 elseif (button ==95) then lmc_send_input(124, 0, 0)
                         lmc_send_input(95, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(95, 0, 2)
()
 elseif (button ==96) then lmc_send_input(124, 0, 0)
                         lmc_send_input(96, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(96, 0, 2)
()
 elseif (button ==97) then lmc_send_input(124, 0, 0)
                         lmc_send_input(97, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(97, 0, 2)
()
 elseif (button ==98) then lmc_send_input(124, 0, 0)
                         lmc_send_input(98, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(98, 0, 2)
()
 elseif (button ==99) then lmc_send_input(124, 0, 0)
                         lmc_send_input(99, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(99, 0, 2)
()
 elseif (button ==100) then lmc_send_input(124, 0, 0)
                         lmc_send_input(100, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(100, 0, 2)
()
 elseif (button ==101) then lmc_send_input(124, 0, 0)
                         lmc_send_input(101, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(101, 0, 2)
()
 elseif (button ==102) then lmc_send_input(124, 0, 0)
                         lmc_send_input(102, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(102, 0, 2)
()
 elseif (button ==103) then lmc_send_input(124, 0, 0)
                         lmc_send_input(103, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(103, 0, 2)
()
 elseif (button ==104) then lmc_send_input(124, 0, 0)
                         lmc_send_input(104, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(104, 0, 2)
()
 elseif (button ==105) then lmc_send_input(124, 0, 0)
                         lmc_send_input(105, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(105, 0, 2)
()
 elseif (button ==106) then lmc_send_input(124, 0, 0)
                         lmc_send_input(106, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(106, 0, 2)
()
 elseif (button ==107) then lmc_send_input(124, 0, 0)
                         lmc_send_input(107, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(107, 0, 2)
()
 elseif (button ==108) then lmc_send_input(124, 0, 0)
                         lmc_send_input(108, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(108, 0, 2)
()
 elseif (button ==109) then lmc_send_input(124, 0, 0)
                         lmc_send_input(109, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(109, 0, 2)
()
 elseif (button ==110) then lmc_send_input(124, 0, 0)
                         lmc_send_input(110, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(110, 0, 2)
()
 elseif (button ==111) then lmc_send_input(124, 0, 0)
                         lmc_send_input(111, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(111, 0, 2)
()
 elseif (button ==112) then lmc_send_input(124, 0, 0)
                         lmc_send_input(112, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(112, 0, 2)
()
 elseif (button ==113) then lmc_send_input(124, 0, 0)
                         lmc_send_input(113, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(113, 0, 2)
()
 elseif (button ==114) then lmc_send_input(124, 0, 0)
                         lmc_send_input(114, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(114, 0, 2)
()
 elseif (button ==115) then lmc_send_input(124, 0, 0)
                         lmc_send_input(115, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(115, 0, 2)
()
 elseif (button ==116) then lmc_send_input(124, 0, 0)
                         lmc_send_input(116, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(116, 0, 2)
()
 elseif (button ==117) then lmc_send_input(124, 0, 0)
                         lmc_send_input(117, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(117, 0, 2)
()
 elseif (button ==118) then lmc_send_input(124, 0, 0)
                         lmc_send_input(118, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(118, 0, 2)
()
 elseif (button ==119) then lmc_send_input(124, 0, 0)
                         lmc_send_input(119, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(119, 0, 2)
()
 elseif (button ==120) then lmc_send_input(124, 0, 0)
                         lmc_send_input(120, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(120, 0, 2)
()
 elseif (button ==121) then lmc_send_input(124, 0, 0)
                         lmc_send_input(121, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(121, 0, 2)
()
 elseif (button ==122) then lmc_send_input(124, 0, 0)
                         lmc_send_input(122, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(122, 0, 2)
()
 elseif (button ==123) then lmc_send_input(124, 0, 0)
                         lmc_send_input(123, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(123, 0, 2)
()
 elseif (button ==124) then lmc_send_input(124, 0, 0)
                         lmc_send_input(124, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(124, 0, 2)
()
 elseif (button ==125) then lmc_send_input(124, 0, 0)
                         lmc_send_input(125, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(125, 0, 2)
()
 elseif (button ==126) then lmc_send_input(124, 0, 0)
                         lmc_send_input(126, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(126, 0, 2)
()
 elseif (button ==127) then lmc_send_input(124, 0, 0)
                         lmc_send_input(127, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(127, 0, 2)
()
 elseif (button ==128) then lmc_send_input(124, 0, 0)
                         lmc_send_input(128, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(128, 0, 2)
()
 elseif (button ==129) then lmc_send_input(124, 0, 0)
                         lmc_send_input(129, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(129, 0, 2)
()
 elseif (button ==130) then lmc_send_input(124, 0, 0)
                         lmc_send_input(130, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(130, 0, 2)
()
 elseif (button ==131) then lmc_send_input(124, 0, 0)
                         lmc_send_input(131, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(131, 0, 2)
()
 elseif (button ==132) then lmc_send_input(124, 0, 0)
                         lmc_send_input(132, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(132, 0, 2)
()
 elseif (button ==133) then lmc_send_input(124, 0, 0)
                         lmc_send_input(133, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(133, 0, 2)
()
 elseif (button ==134) then lmc_send_input(124, 0, 0)
                         lmc_send_input(134, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(134, 0, 2)
()
 elseif (button ==135) then lmc_send_input(124, 0, 0)
                         lmc_send_input(135, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(135, 0, 2)
()
 elseif (button ==136) then lmc_send_input(124, 0, 0)
                         lmc_send_input(136, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(136, 0, 2)
()
 elseif (button ==137) then lmc_send_input(124, 0, 0)
                         lmc_send_input(137, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(137, 0, 2)
()
 elseif (button ==138) then lmc_send_input(124, 0, 0)
                         lmc_send_input(138, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(138, 0, 2)
()
 elseif (button ==139) then lmc_send_input(124, 0, 0)
                         lmc_send_input(139, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(139, 0, 2)
()
 elseif (button ==140) then lmc_send_input(124, 0, 0)
                         lmc_send_input(140, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(140, 0, 2)
()
 elseif (button ==141) then lmc_send_input(124, 0, 0)
                         lmc_send_input(141, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(141, 0, 2)
()
 elseif (button ==142) then lmc_send_input(124, 0, 0)
                         lmc_send_input(142, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(142, 0, 2)
()
 elseif (button ==143) then lmc_send_input(124, 0, 0)
                         lmc_send_input(143, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(143, 0, 2)
()
 elseif (button ==144) then lmc_send_input(124, 0, 0)
                         lmc_send_input(144, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(144, 0, 2)
()
 elseif (button ==145) then lmc_send_input(124, 0, 0)
                         lmc_send_input(145, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(145, 0, 2)
()
 elseif (button ==146) then lmc_send_input(124, 0, 0)
                         lmc_send_input(146, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(146, 0, 2)
()
 elseif (button ==147) then lmc_send_input(124, 0, 0)
                         lmc_send_input(147, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(147, 0, 2)
()
 elseif (button ==148) then lmc_send_input(124, 0, 0)
                         lmc_send_input(148, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(148, 0, 2)
()
 elseif (button ==149) then lmc_send_input(124, 0, 0)
                         lmc_send_input(149, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(149, 0, 2)
()
 elseif (button ==150) then lmc_send_input(124, 0, 0)
                         lmc_send_input(150, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(150, 0, 2)
()
 elseif (button ==151) then lmc_send_input(124, 0, 0)
                         lmc_send_input(151, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(151, 0, 2)
()
 elseif (button ==152) then lmc_send_input(124, 0, 0)
                         lmc_send_input(152, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(152, 0, 2)
()
 elseif (button ==153) then lmc_send_input(124, 0, 0)
                         lmc_send_input(153, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(153, 0, 2)
()
 elseif (button ==154) then lmc_send_input(124, 0, 0)
                         lmc_send_input(154, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(154, 0, 2)
()
 elseif (button ==155) then lmc_send_input(124, 0, 0)
                         lmc_send_input(155, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(155, 0, 2)
()
 elseif (button ==156) then lmc_send_input(124, 0, 0)
                         lmc_send_input(156, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(156, 0, 2)
()
 elseif (button ==157) then lmc_send_input(124, 0, 0)
                         lmc_send_input(157, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(157, 0, 2)
()
 elseif (button ==158) then lmc_send_input(124, 0, 0)
                         lmc_send_input(158, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(158, 0, 2)
()
 elseif (button ==159) then lmc_send_input(124, 0, 0)
                         lmc_send_input(159, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(159, 0, 2)
()
 elseif (button ==160) then lmc_send_input(124, 0, 0)
                         lmc_send_input(160, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(160, 0, 2)
()
 elseif (button ==161) then lmc_send_input(124, 0, 0)
                         lmc_send_input(161, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(161, 0, 2)
()
 elseif (button ==162) then lmc_send_input(124, 0, 0)
                         lmc_send_input(162, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(162, 0, 2)
()
 elseif (button ==163) then lmc_send_input(124, 0, 0)
                         lmc_send_input(163, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(163, 0, 2)
()
 elseif (button ==164) then lmc_send_input(124, 0, 0)
                         lmc_send_input(164, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(164, 0, 2)
()
 elseif (button ==165) then lmc_send_input(124, 0, 0)
                         lmc_send_input(165, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(165, 0, 2)
()
 elseif (button ==166) then lmc_send_input(124, 0, 0)
                         lmc_send_input(166, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(166, 0, 2)
()
 elseif (button ==167) then lmc_send_input(124, 0, 0)
                         lmc_send_input(167, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(167, 0, 2)
()
 elseif (button ==168) then lmc_send_input(124, 0, 0)
                         lmc_send_input(168, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(168, 0, 2)
()
 elseif (button ==169) then lmc_send_input(124, 0, 0)
                         lmc_send_input(169, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(169, 0, 2)
()
 elseif (button ==170) then lmc_send_input(124, 0, 0)
                         lmc_send_input(170, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(170, 0, 2)
()
 elseif (button ==171) then lmc_send_input(124, 0, 0)
                         lmc_send_input(171, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(171, 0, 2)
()
 elseif (button ==172) then lmc_send_input(124, 0, 0)
                         lmc_send_input(172, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(172, 0, 2)
()
 elseif (button ==173) then lmc_send_input(124, 0, 0)
                         lmc_send_input(173, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(173, 0, 2)
()
 elseif (button ==174) then lmc_send_input(124, 0, 0)
                         lmc_send_input(174, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(174, 0, 2)
()
 elseif (button ==175) then lmc_send_input(124, 0, 0)
                         lmc_send_input(175, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(175, 0, 2)
()
 elseif (button ==176) then lmc_send_input(124, 0, 0)
                         lmc_send_input(176, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(176, 0, 2)
()
 elseif (button ==177) then lmc_send_input(124, 0, 0)
                         lmc_send_input(177, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(177, 0, 2)
()
 elseif (button ==178) then lmc_send_input(124, 0, 0)
                         lmc_send_input(178, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(178, 0, 2)
()
 elseif (button ==179) then lmc_send_input(124, 0, 0)
                         lmc_send_input(179, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(179, 0, 2)
()
 elseif (button ==180) then lmc_send_input(124, 0, 0)
                         lmc_send_input(180, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(180, 0, 2)
()
 elseif (button ==181) then lmc_send_input(124, 0, 0)
                         lmc_send_input(181, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(181, 0, 2)
()
 elseif (button ==182) then lmc_send_input(124, 0, 0)
                         lmc_send_input(182, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(182, 0, 2)
()
 elseif (button ==183) then lmc_send_input(124, 0, 0)
                         lmc_send_input(183, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(183, 0, 2)
()
 elseif (button ==184) then lmc_send_input(124, 0, 0)
                         lmc_send_input(184, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(184, 0, 2)
()
 elseif (button ==185) then lmc_send_input(124, 0, 0)
                         lmc_send_input(185, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(185, 0, 2)
()
 elseif (button ==186) then lmc_send_input(124, 0, 0)
                         lmc_send_input(186, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(186, 0, 2)
()
 elseif (button ==187) then lmc_send_input(124, 0, 0)
                         lmc_send_input(187, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(187, 0, 2)
()
 elseif (button ==188) then lmc_send_input(124, 0, 0)
                         lmc_send_input(188, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(188, 0, 2)
()
 elseif (button ==189) then lmc_send_input(124, 0, 0)
                         lmc_send_input(189, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(189, 0, 2)
()
 elseif (button ==190) then lmc_send_input(124, 0, 0)
                         lmc_send_input(190, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(190, 0, 2)
()
 elseif (button ==191) then lmc_send_input(124, 0, 0)
                         lmc_send_input(191, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(191, 0, 2)
()
 elseif (button ==192) then lmc_send_input(124, 0, 0)
                         lmc_send_input(192, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(192, 0, 2)
()
 elseif (button ==193) then lmc_send_input(124, 0, 0)
                         lmc_send_input(193, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(193, 0, 2)
()
 elseif (button ==194) then lmc_send_input(124, 0, 0)
                         lmc_send_input(194, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(194, 0, 2)
()
 elseif (button ==195) then lmc_send_input(124, 0, 0)
                         lmc_send_input(195, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(195, 0, 2)
()
 elseif (button ==196) then lmc_send_input(124, 0, 0)
                         lmc_send_input(196, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(196, 0, 2)
()
 elseif (button ==197) then lmc_send_input(124, 0, 0)
                         lmc_send_input(197, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(197, 0, 2)
()
 elseif (button ==198) then lmc_send_input(124, 0, 0)
                         lmc_send_input(198, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(198, 0, 2)
()
 elseif (button ==199) then lmc_send_input(124, 0, 0)
                         lmc_send_input(199, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(199, 0, 2)
()
 elseif (button ==200) then lmc_send_input(124, 0, 0)
                         lmc_send_input(200, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(200, 0, 2)
()
 elseif (button ==201) then lmc_send_input(124, 0, 0)
                         lmc_send_input(201, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(201, 0, 2)
()
 elseif (button ==202) then lmc_send_input(124, 0, 0)
                         lmc_send_input(202, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(202, 0, 2)
()
 elseif (button ==203) then lmc_send_input(124, 0, 0)
                         lmc_send_input(203, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(203, 0, 2)
()
 elseif (button ==204) then lmc_send_input(124, 0, 0)
                         lmc_send_input(204, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(204, 0, 2)
()
 elseif (button ==205) then lmc_send_input(124, 0, 0)
                         lmc_send_input(205, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(205, 0, 2)
()
 elseif (button ==206) then lmc_send_input(124, 0, 0)
                         lmc_send_input(206, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(206, 0, 2)
()
 elseif (button ==207) then lmc_send_input(124, 0, 0)
                         lmc_send_input(207, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(207, 0, 2)
()
 elseif (button ==208) then lmc_send_input(124, 0, 0)
                         lmc_send_input(208, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(208, 0, 2)
()
 elseif (button ==209) then lmc_send_input(124, 0, 0)
                         lmc_send_input(209, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(209, 0, 2)
()
 elseif (button ==210) then lmc_send_input(124, 0, 0)
                         lmc_send_input(210, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(210, 0, 2)
()
 elseif (button ==211) then lmc_send_input(124, 0, 0)
                         lmc_send_input(211, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(211, 0, 2)
()
 elseif (button ==212) then lmc_send_input(124, 0, 0)
                         lmc_send_input(212, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(212, 0, 2)
()
 elseif (button ==213) then lmc_send_input(124, 0, 0)
                         lmc_send_input(213, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(213, 0, 2)
()
 elseif (button ==214) then lmc_send_input(124, 0, 0)
                         lmc_send_input(214, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(214, 0, 2)
()
 elseif (button ==215) then lmc_send_input(124, 0, 0)
                         lmc_send_input(215, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(215, 0, 2)
()
 elseif (button ==216) then lmc_send_input(124, 0, 0)
                         lmc_send_input(216, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(216, 0, 2)
()
 elseif (button ==217) then lmc_send_input(124, 0, 0)
                         lmc_send_input(217, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(217, 0, 2)
()
 elseif (button ==218) then lmc_send_input(124, 0, 0)
                         lmc_send_input(218, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(218, 0, 2)
()
 elseif (button ==219) then lmc_send_input(124, 0, 0)
                         lmc_send_input(219, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(219, 0, 2)
()
 elseif (button ==220) then lmc_send_input(124, 0, 0)
                         lmc_send_input(220, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(220, 0, 2)
()
 elseif (button ==221) then lmc_send_input(124, 0, 0)
                         lmc_send_input(221, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(221, 0, 2)
()
 elseif (button ==222) then lmc_send_input(124, 0, 0)
                         lmc_send_input(222, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(222, 0, 2)
()
 elseif (button ==223) then lmc_send_input(124, 0, 0)
                         lmc_send_input(223, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(223, 0, 2)
()
 elseif (button ==224) then lmc_send_input(124, 0, 0)
                         lmc_send_input(224, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(224, 0, 2)
()
 elseif (button ==225) then lmc_send_input(124, 0, 0)
                         lmc_send_input(225, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(225, 0, 2)
()
 elseif (button ==226) then lmc_send_input(124, 0, 0)
                         lmc_send_input(226, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(226, 0, 2)
()
 elseif (button ==227) then lmc_send_input(124, 0, 0)
                         lmc_send_input(227, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(227, 0, 2)
()
 elseif (button ==228) then lmc_send_input(124, 0, 0)
                         lmc_send_input(228, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(228, 0, 2)
()
 elseif (button ==229) then lmc_send_input(124, 0, 0)
                         lmc_send_input(229, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(229, 0, 2)
()
 elseif (button ==230) then lmc_send_input(124, 0, 0)
                         lmc_send_input(230, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(230, 0, 2)
()
 elseif (button ==231) then lmc_send_input(124, 0, 0)
                         lmc_send_input(231, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(231, 0, 2)
()
 elseif (button ==232) then lmc_send_input(124, 0, 0)
                         lmc_send_input(232, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(232, 0, 2)
()
 elseif (button ==233) then lmc_send_input(124, 0, 0)
                         lmc_send_input(233, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(233, 0, 2)
()
 elseif (button ==234) then lmc_send_input(124, 0, 0)
                         lmc_send_input(234, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(234, 0, 2)
()
 elseif (button ==235) then lmc_send_input(124, 0, 0)
                         lmc_send_input(235, 0, 0)
                         lmc_send_input(124, 0, 2)
                         lmc_send_input(235, 0, 2)
















else print('Not yet assigned: ' .. button)
end
end)
             
